twilio:
  url: ${TWILIO_URL}
  fromWhats: ${TWILIO_FROM_WHATS}
  fromSMS: ${TWILIO_FROM_SMS}
  account: ${TWILIO_ACCOUNT}
  authToken: ${TWILIO_AUTH_TOKEN}
email:
  key: ${EMAIL_KEY}
  account: ${EMAIL_ACCOUNT} 
